[tool.black]
line-length = 120
skip-string-normalization = true

[tool.isort]
line_length = 120
balanced_wrapping = true
use_parentheses = true
include_trailing_comma = true
force_grid_wrap = 0
multi_line_output = 3
ensure_newline_before_comments = true
